steps:
  - name: gcr.io/cloud-builders/docker
    id: build-fetcher
    args: ["build", "-f", "autobet/sports/Dockerfile.fetcher", "-t", "$_IMAGE_FETCHER", "."]
  - name: gcr.io/cloud-builders/docker
    id: push-fetcher
    args: ["push", "$_IMAGE_FETCHER"]
  - name: gcr.io/cloud-builders/docker
    id: build-orchestrator
    args: ["build", "-f", "autobet/sports/Dockerfile.orchestrator", "-t", "$_IMAGE_ORCHESTRATOR", "."]
  - name: gcr.io/cloud-builders/docker
    id: push-orchestrator
    args: ["push", "$_IMAGE_ORCHESTRATOR"]
  - name: gcr.io/cloud-builders/docker
    id: build-websocket
    args: ["build", "-f", "autobet/sports/Dockerfile.websocket", "-t", "$_IMAGE_WEBSOCKET", "."]
  - name: gcr.io/cloud-builders/docker
    id: push-websocket
    args: ["push", "$_IMAGE_WEBSOCKET"]
  - name: gcr.io/cloud-builders/docker
    id: build-superfecta
    args: ["build", "-f", "autobet/sports/Dockerfile.superfecta", "-t", "$_IMAGE_SUPERFECTA", "."]
  - name: gcr.io/cloud-builders/docker
    id: push-superfecta
    args: ["push", "$_IMAGE_SUPERFECTA"]
substitutions:
  _IMAGE_FETCHER: ""
  _IMAGE_ORCHESTRATOR: ""
  _IMAGE_WEBSOCKET: ""
  _IMAGE_SUPERFECTA: ""
timeout: "1800s"
images:
  - "$_IMAGE_FETCHER"
  - "$_IMAGE_ORCHESTRATOR"
  - "$_IMAGE_WEBSOCKET"
  - "$_IMAGE_SUPERFECTA"
