name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  python-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Import smoke tests
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          python - << 'PY'
          import importlib
          # Ensure both import styles work
          import sports
          import autobet.sports as ab_sports
          # Import key modules without executing network paths
          importlib.import_module('sports.run')
          importlib.import_module('sports.webapp')
          print('Imports OK')
          PY

      - name: CLI help smoke
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: |
          python -m sports.run --help

